AWSTemplateFormatVersion: 2010-09-09
Description: LMS Project CloudFormation template.
Resources:
  lmsVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
       - Key: Name
         Value: lms-vpc

  lmswebSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref lmsVPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: "us-east-2a"
      MapPublicIpOnLaunch: "true"
      Tags:
      - Key: Name
        Value: lms-web-subnet            

  lmsapiSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref lmsVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: "us-east-2a"
      MapPublicIpOnLaunch: "true"
      Tags:
      - Key: Name
        Value: lms-api-subnet 

  lmsdbSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref lmsVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: "us-east-2a"
      MapPublicIpOnLaunch: "false"
      Tags:
      - Key: Name
        Value: lms-database-subnet 

  lmsInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: lms-internet-gateway
  
  lmsAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: lmsVPC
      InternetGatewayId:
        Ref: lmsInternetGateway  

  lmspublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: lmsVPC
      Tags:
      - Key: Name
        Value: lms-public-rt

  lmsinternetRoute:
    Type: AWS::EC2::Route
    DependsOn: lmsAttachGateway
    Properties:
       RouteTableId:
         Ref: lmspublicRouteTable
       DestinationCidrBlock: 0.0.0.0/0
       GatewayId:
         Ref: lmsInternetGateway